site_name: Bracex
site_url: https://facelessuser.github.io/bracex
repo_url: https://github.com/facelessuser/bracex
edit_uri: tree/master/docs/src/markdown
site_description: Python spell checker.
copyright: |
  Copyright &copy; 2018 - 2020 <a href="https://github.com/facelessuser"  target="_blank" rel="noopener">Isaac Muse</a>

docs_dir: docs/src/markdown
theme:
  name: material
  icon:
    logo: material/book-open-page-variant
  palette:
    primary: drac-purple
    accent: drac-purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs

nav:
  - Usage:
    - Bracex: index.md
  - About:
    - Contributing &amp; Support: about/contributing.md
    - Development: about/development.md
    - Changelog: about/changelog.md
    - License: about/license.md

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      user: facelessuser
      repo: bracex
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/facelessuser
    - icon: fontawesome/brands/discord
      link: https://discord.gg/hZSsa8R

plugins:
  - search
  - git-revision-date-localized
  - minify:
      minify_html: true
  - mkdocs_pymdownx_material_extras
